-- ============================================================
-- Wait-Light — Secure Rotating QR Token system
-- Adds the qr_tokens table, RLS policies, the validate_qr_token
-- RPC, and a cron job to purge expired tokens.
-- ============================================================

-- ──────────────────────────────────────────────────────────────
-- TABLE: qr_tokens
-- One row per generated QR token. Rotates every 15 s.
-- TTL: 30 s (expires_at). Single-use: used = true after scan.
-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS qr_tokens (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    merchant_id UUID        NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
    nonce       TEXT        NOT NULL UNIQUE,
    used        BOOLEAN     NOT NULL DEFAULT false,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at  TIMESTAMPTZ NOT NULL DEFAULT NOW() + INTERVAL '30 seconds'
);

COMMENT ON TABLE qr_tokens IS
    'Short-lived, single-use tokens embedded in the rotating QR code. '
    'Generated by the merchant dashboard every 15 s, valid for 30 s.';

COMMENT ON COLUMN qr_tokens.nonce IS
    'Cryptographic nonce: UUID + HMAC-SHA256 hex. ~256 bits of entropy.';

COMMENT ON COLUMN qr_tokens.used IS
    'Set to true atomically by validate_qr_token() on first use. '
    'Prevents replay attacks — a token can never be consumed twice.';

COMMENT ON COLUMN qr_tokens.expires_at IS
    '30-second TTL. Longer than the 15-second rotation interval so two '
    'tokens are valid simultaneously (handles scan-at-rotation-boundary).';

-- ──────────────────────────────────────────────────────────────
-- INDEXES
-- ──────────────────────────────────────────────────────────────

-- Fast lookup when validating a token by nonce + merchant
CREATE INDEX IF NOT EXISTS idx_qr_tokens_merchant_nonce
    ON qr_tokens (merchant_id, nonce);

-- Fast cleanup scan by expiry time (used by cron job)
CREATE INDEX IF NOT EXISTS idx_qr_tokens_expires
    ON qr_tokens (expires_at);

-- ──────────────────────────────────────────────────────────────
-- ROW LEVEL SECURITY
-- ──────────────────────────────────────────────────────────────
ALTER TABLE qr_tokens ENABLE ROW LEVEL SECURITY;

-- INSERT: only the authenticated merchant can generate tokens for themselves
CREATE POLICY "qr_tokens_merchant_insert"
    ON qr_tokens FOR INSERT
    WITH CHECK (auth.uid() = merchant_id);

-- SELECT: public (anon) — required so the customer join page can
-- look up a token via validate_qr_token() RPC, which runs SECURITY DEFINER.
-- The RPC itself enforces all security checks; this policy is the gate
-- that allows the anon role to call the RPC at all.
CREATE POLICY "qr_tokens_public_read"
    ON qr_tokens FOR SELECT
    USING (true);

-- UPDATE: explicitly denied for all roles.
-- The only legitimate update (setting used = true) is done inside
-- validate_qr_token() which runs as SECURITY DEFINER (bypasses RLS).
CREATE POLICY "qr_tokens_no_direct_update"
    ON qr_tokens FOR UPDATE
    USING (false);

-- DELETE: explicitly denied for all roles.
-- Expired tokens are removed only by the cron job below
-- using a SECURITY DEFINER function (bypasses RLS).
CREATE POLICY "qr_tokens_no_direct_delete"
    ON qr_tokens FOR DELETE
    USING (false);

-- ──────────────────────────────────────────────────────────────
-- RPC: validate_qr_token
-- Called by the customer join page (/[slug]/join?token=<nonce>).
-- Atomically checks validity and marks the token as used in a
-- single transaction — prevents race conditions where two people
-- scan the same QR frame simultaneously.
--
-- Returns TRUE  → token valid, consumed, customer may join.
-- Returns FALSE → token invalid, expired, already used, or
--                 merchant/slug not found.
-- ──────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION validate_qr_token(p_nonce TEXT, p_slug TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_merchant_id UUID;
    v_token_id    UUID;
BEGIN
    -- 1. Resolve slug → merchant_id
    SELECT id INTO v_merchant_id
        FROM merchants
        WHERE slug = p_slug;

    IF v_merchant_id IS NULL THEN
        RETURN false;
    END IF;

    -- 2. Find a valid, unused, non-expired token matching the nonce
    SELECT id INTO v_token_id
        FROM qr_tokens
        WHERE nonce      = p_nonce
          AND merchant_id = v_merchant_id
          AND used        = false
          AND expires_at  > NOW()
        FOR UPDATE SKIP LOCKED;   -- advisory lock: handles concurrent scans

    IF v_token_id IS NULL THEN
        RETURN false;
    END IF;

    -- 3. Atomically mark as consumed — no second use possible
    UPDATE qr_tokens
        SET used = true
        WHERE id = v_token_id;

    RETURN true;
END;
$$;

-- Revoke direct execute from anon/authenticated — it's called via Supabase RPC
-- which already enforces proper session context.
REVOKE ALL ON FUNCTION validate_qr_token(TEXT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION validate_qr_token(TEXT, TEXT) TO anon, authenticated;

COMMENT ON FUNCTION validate_qr_token IS
    'Atomically validates and consumes a QR token. '
    'Returns true only if the token exists, is not expired, and has not been used. '
    'Uses FOR UPDATE SKIP LOCKED to handle simultaneous scans without a race condition.';

-- ──────────────────────────────────────────────────────────────
-- RPC: cleanup_expired_qr_tokens (SECURITY DEFINER)
-- Called by the pg_cron job below. Deletes tokens that expired
-- more than 5 minutes ago (safety window beyond the 30 s TTL).
-- ──────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION cleanup_expired_qr_tokens()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    deleted_count INTEGER;
BEGIN
    DELETE FROM qr_tokens
        WHERE expires_at < NOW() - INTERVAL '5 minutes';

    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    RETURN deleted_count;
END;
$$;

REVOKE ALL ON FUNCTION cleanup_expired_qr_tokens() FROM PUBLIC;

COMMENT ON FUNCTION cleanup_expired_qr_tokens IS
    'Purges expired QR tokens. Called by pg_cron every 5 minutes. '
    'Keeps tokens for 5 minutes past expiry as a forensic safety window.';

-- ──────────────────────────────────────────────────────────────
-- CRON JOB: purge expired tokens every 5 minutes
--
-- Requires the pg_cron extension. Enable it first in the Supabase
-- Dashboard → Database → Extensions → pg_cron, then re-run this
-- block (or run it manually in the SQL editor).
--
-- The DO block below registers the job when pg_cron is available
-- and silently skips it when it is not — the migration never fails.
-- ──────────────────────────────────────────────────────────────
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_extension WHERE extname = 'pg_cron'
    ) THEN
        PERFORM cron.schedule(
            'cleanup-qr-tokens',
            '*/5 * * * *',
            'SELECT cleanup_expired_qr_tokens()'
        );
        RAISE NOTICE 'pg_cron job "cleanup-qr-tokens" registered successfully.';
    ELSE
        RAISE NOTICE
            'pg_cron is not enabled. Enable it in the Supabase Dashboard '
            '(Database → Extensions → pg_cron) then run: '
            'SELECT cron.schedule(''cleanup-qr-tokens'', ''*/5 * * * *'', '
            '''SELECT cleanup_expired_qr_tokens()'');';
    END IF;
END;
$$;
